# application.yml
server:
  port: 9111

spring:
  profiles:
    active: production
---

spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:mysql://localhost:3306/impot
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

---

spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:mysql://localhost:3306/impot
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

---

spring:
  config:
    activate:
      on-profile: production

  datasource:
    url: jdbc:mysql://localhost:3306/impot
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  main:
    web-application-type: none


